#!/bin/bash

set -ex

if [[ $( git symbolic-ref --short HEAD) = "master" ]]; then
   echo "Please commit with new branch rather than master"
   exit 1
fi

# Filter Golang files match Added (A), Copied (C), Modified (M) conditions.
gofiles=`git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true`

if [ -n "$gofiles" ]; then
    gofmt -s -w $gofiles
    goimports -w $gofiles
    git add $gofiles
fi

golangci-lint run --fix